// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/generate-kanji-index.ts on `npm run predev` / `npm run prebuild`.
// Sources: vol1_kanji.json, vol2_kanji.json

import vol1 from "../materials/vol1_kanji.json";
import vol2 from "../materials/vol2_kanji.json";

import type { RawVolume } from "./kanji";

export const rawKanjiVolumes: RawVolume[] = [vol1, vol2];
