// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/generate-kanji-index.ts on `npm run predev` / `npm run prebuild`.
// Sources: vol1_kanji.json, vol2_kanji.json, vol3_kanji.json, vol4_kanji.json, vol5_kanji.json, vol6_kanji.json

import vol1 from "../materials/vol1_kanji.json";
import vol2 from "../materials/vol2_kanji.json";
import vol3 from "../materials/vol3_kanji.json";
import vol4 from "../materials/vol4_kanji.json";
import vol5 from "../materials/vol5_kanji.json";
import vol6 from "../materials/vol6_kanji.json";

import type { RawVolume } from "./kanji";

export const rawKanjiVolumes: RawVolume[] = [vol1, vol2, vol3, vol4, vol5, vol6];
