import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(process.cwd());
const materialsDir = path.join(repoRoot, "materials");
const outFile = path.join(repoRoot, "data", "kanji-volumes.generated.ts");

const VOLUME_RE = /^vol(\d+)_kanji\.json$/;

const files = fs
  .readdirSync(materialsDir)
  .map((f) => {
    const m = f.match(VOLUME_RE);
    return m ? { file: f, num: parseInt(m[1], 10) } : null;
  })
  .filter((x): x is { file: string; num: number } => x !== null)
  .sort((a, b) => a.num - b.num);

if (files.length === 0) {
  console.warn(
    "[generate-kanji-index] no vol*_kanji.json files found in materials/.",
  );
}

const importLines = files
  .map((f, i) => `import vol${i + 1} from "../materials/${f.file}";`)
  .join("\n");

const arrayLine = files.length
  ? `[${files.map((_, i) => `vol${i + 1}`).join(", ")}]`
  : "[]";

const header = `// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/generate-kanji-index.ts on \`npm run predev\` / \`npm run prebuild\`.
// Sources: ${files.map((f) => f.file).join(", ") || "(none)"}
`;

const body = `${header}
${importLines}

import type { RawVolume } from "./kanji";

export const rawKanjiVolumes: RawVolume[] = ${arrayLine};
`;

fs.writeFileSync(outFile, body, "utf-8");
console.log(
  `[generate-kanji-index] wrote ${path.relative(repoRoot, outFile)} with ${files.length} volume(s).`,
);
